### ISSUE TITLE
Using manylinux2010 for x86_64 linux?

### ISSUE THREAD

**Issue by cocoa-xu** [cocoa-xu/evision#211]
Link to a previous issue #196. 

Using manylinux2010 (quay.io/pypa/manylinux2010_x86_64:latest) should make it compatible with most versions of Linux (x86_64).

**Comment by cocoa-xu** [comment]
manylinux2010 is a little bit too old:

```
asmjit/core/cpuinfo.cpp:18:12: fatal error: sys/auxv.h: No such file or directory
   #include <sys/auxv.h>
```

Also see, https://github.com/conda-forge/conda-forge.github.io/issues/1625#issuecomment-1377192685

**Comment by cocoa-xu** [comment]
Using manylinux2014 works.

**Comment by cocoa-xu** [comment]
> Using manylinux2014 works.

Actually no. 

```
** (ErlangError) Erlang error: {:notsup, {~c"hash.c", 112}, ~c"Digest type not supported in this cryptolib"}
    (crypto 5.2) crypto.erl:2200: :crypto.hash(:blake2b, "defmodule Decimal.Macros do\n  @moduledoc false\n\n  defmacro doc_since(version) do\n    if Version.match?(System.version(), \">= 1.7.0\") do\n      quote do\n        @doc since: unquote(version)\n      end\n    end\n  end\nend\n")
    (mix 1.15.4) lib/mix/compilers/elixir.ex:1104: Mix.Compilers.Elixir.each_file/5
    (mix 1.15.4) lib/mix/compilers/elixir.ex:1009: Mix.Compilers.Elixir.compiler_loop/4
    (mix 1.15.4) lib/mix/compilers/elixir.ex:173: Mix.Compilers.Elixir.compile/7
    (mix 1.15.4) lib/mix/state.ex:15: Mix.State.lock/2
    (mix 1.15.4) lib/mix/task.ex:447: anonymous fn/3 in Mix.Task.run_task/5
    (mix 1.15.4) lib/mix/tasks/compile.all.ex:124: Mix.Tasks.Compile.All.run_compiler/2
    (mix 1.15.4) lib/mix/tasks/compile.all.ex:104: Mix.Tasks.Compile.All.compile/4
```

Perhaps I need to compile a newer version of openssl first.

**Comment by cocoa-xu** [comment]
It works. And this should lower the required glib version to 2.17. PR coming soon,

**Comment by cocoa-xu** [comment]
Done.
