### ISSUE TITLE
Cannot compile in M1 with macOS ventura

### ISSUE THREAD

**Issue by bernardo-martinez** [cocoa-xu/evision#267]
Hello! I have added it as a dependency to one of my projects and am trying to compile it with no luck, what i get is:

```
mix deps.compile evision

19:07:19.221 [info] EVISION_PREFER_PRECOMPILED: true; try to download and use the precompiled library.

19:07:19.222 [info] Current target `aarch64-apple-darwin` has precompiled binaries.

19:07:19.222 [info] Current host NIF version is `2.17`, will use precompiled binaries with NIF version 2.16.

19:07:19.281 [info] Copying priv directory: /Users/bernardo.martinez/Library/Caches/evision-nif_2.16-aarch64-apple-darwin-contrib-0.2.9/priv => /Users/bernardo.martinez/explorers/app/_build/dev/lib/evision/priv

19:07:19.369 [info] Copying generated Elixir binding files: /Users/bernardo.martinez/Library/Caches/evision-nif_2.16-aarch64-apple-darwin-contrib-0.2.9/elixir_generated => /Users/bernardo.martinez/explorers/app/deps/evision/lib/generated
==> evision
Compiling 672 files (.ex)
could not compile dependency :evision, "mix compile" failed. Errors may have been logged above. You can recompile this dependency with "mix deps.compile evision --force", update it with "mix deps.update evision" or clean it with "mix deps.clean evision"
** (File.Error) could not read file "lib/generated/evision_backgroundsubtractorknn.ex": no such file or directory
    (elixir 1.16.1) lib/file.ex:384: File.read!/1
    (mix 1.16.1) lib/mix/compilers/elixir.ex:1117: Mix.Compilers.Elixir.each_file/5
    (mix 1.16.1) lib/mix/compilers/elixir.ex:1028: Mix.Compilers.Elixir.compiler_loop/4
    (mix 1.16.1) lib/mix/compilers/elixir.ex:172: Mix.Compilers.Elixir.compile/7
    (mix 1.16.1) lib/mix/state.ex:15: Mix.State.lock/2
    (mix 1.16.1) lib/mix/task.ex:478: anonymous fn/3 in Mix.Task.run_task/5
    (mix 1.16.1) lib/mix/tasks/compile.all.ex:124: Mix.Tasks.Compile.All.run_compiler/2
    (mix 1.16.1) lib/mix/tasks/compile.all.ex:104: Mix.Tasks.Compile.All.compile/4
   ```
   
   
   My local setup is:
   ```
   uname -a
Darwin CABESM110441.local 22.6.0 Darwin Kernel Version 22.6.0: Fri Sep 15 13:41:30 PDT 2023; root:xnu-8796.141.3.700.8~1/RELEASE_ARM64_T8103 arm64
```

can you give a hand please?

**Comment by cocoa-xu** [comment]
This is likely a race condition between the `mix` session (the one you're running) and the background Elixir language server. The language server will also try to compile all the deps, including evision. As evision will put pre-generated Elixir module files from the precompiled archive file, this can cause a race condition. 

The easy "fix" is either wait for the language server to complete its job and then run `mix deps.compile` or disable the language server first, run `mix deps.compile` and re-enable the language server after evision is compiled.
